### ISSUE TITLE
ES 2.4 MapperParsingException[Cannot generate dynamic mappings of type [_id] for [_id]]

### ISSUE THREAD

**Issue by srdjan-catalyst** [LibreCat/Catmandu-Store-Elasticsearch#10]
This is what I get with ES 2.4:
[2016-10-06 18:46:53,494][DEBUG][action.bulk              ] [srdjan] [koha_biblios][0] failed to execute bulk item (index) index {[koha_biblios][data][48D20566-8B88-11E6-8DDB-2C262B09EC5D], source[{"title":"New Zealand Food Safety Authority Annual Report 2007 - 2008","onloan":"0","record":[["LDR",null,null,"_","00249pam a2200085 a 4500"],["856"," "," ","u","www.nzfsa.govt.nz"],["260"," "," ","b","New Zealand Food Safety Authority"],["245"," "," ","a","New Zealand Food Safety Authority Annual Report 2007 - 2008"],["500"," "," ","a","Holdings: latest only"],["952"," "," ","0","0","1","0","4","0","6","ANNUAL_REPORT_N","7","0","9","10338","a","CORP","b","CORP","d","2010-06-17","g","0.00","o","Annual Report: N","r","2010-06-17","w","2010-06-17","y","BK"],["999"," "," ","c","48","d","48"]],"_id":"48D20566-8B88-11E6-8DDB-2C262B09EC5D","publisher__facet":"New Zealand Food Safety Authority","Local-number":"48","publisher":"New Zealand Food Safety Authority","title__suggestion":{"input":["New Zealand Food Safety Authority Annual Report 2007 - 2008"]}}]}
MapperParsingException[Cannot generate dynamic mappings of type [_id] for [_id]]
        at org.elasticsearch.index.mapper.DocumentParser.createBuilderFromFieldType(DocumentParser.java:506)
        at org.elasticsearch.index.mapper.DocumentParser.parseDynamicValue(DocumentParser.java:616)
        at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:444)
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:264)
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:124)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:580)
        at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:559)
        at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:211)
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:223)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:327)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:120)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:657)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:287)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

When I change
--- /usr/share/perl5/Catmandu/Store/ElasticSearch/Bag.pm        2016-10-04 15:56:58.000000000 +1300
+++ /home/srdjan/Bag.pm 2016-10-06 19:33:26.010399861 +1300
@@ -78,7 +78,7 @@
 sub add {
     my ($self, $data) = @_;
     $data = {%$data};
-    my $id = $data->{$self->id_key};
-    my $id = delete $data->{$self->id_key};
   $self->_bulk->index({
       id     => $id,
       source => $data,
  all goes fine.
  Did I miss anything in configuration?
  Thanks, Srdjan

**Comment by nics** [comment]
Hello Srdjan,

can you include you store configuration?

Regards,
Nicolas

--
Nicolas Steenlant
Ghent University Library

Sint-Hubertusstraat 8
9000 Gent

nicolas.steenlant@ugent.be
+32 486 62 62 27

**Comment by srdjan-catalyst** [comment]
Hi Nicolas,
Sorry for the delay, did not get a notification.
Is this what you are looking for:
http://www.mediafire.com/file/jtzkh4xjql8yp5g/elasticsearch.yml

Thanks,
Srdjan

**Comment by nics** [comment]
Hello Srdjan, now it's me who missed your comment. You need to set id_key to something else than _id for ElasticSearch > 2.0. More info here: https://metacpan.org/pod/Catmandu::Store::ElasticSearch#COMPATIBILITY

**Comment by srdjan-catalyst** [comment]
Hi Nicolas,

Thanks for that. Some other people made it work with v5, I assume they
renamed the key, so all good now.

Cheers,
Srdjan
