### ISSUE TITLE
Prepare for Elasticsearch 2.0

### ISSUE THREAD

**Issue by nics** [LibreCat/Catmandu-Store-Elasticsearch#7]
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking-changes-2.0.html
https://www.elastic.co/blog/elasticsearch-2-0-0-rc1-released

**Comment by phochste** [comment]
The Catmandu::Store::ElasticSearch seems to be broken on Elasticsearch 2.2.0 installations. The '_id' field isn't supported:

        [2016-02-08 14:38:57,513][DEBUG][action.bulk              ] [Terminus] [catmandu][0] failed to execute bulk item (index) index {[catmandu][data][4D4DA262-CE69-11E5-A1C4-BD8E0F71BF90], source[{"name":"Patrick","_id":"4D4DA262-CE69-11E5-A1C4-BD8E0F71BF90"}]}
java.lang.IllegalArgumentException: Field [_id] is defined twice in [data]
	at org.elasticsearch.index.mapper.MapperService.checkFieldUniqueness(MapperService.java:377)
	at org.elasticsearch.index.mapper.MapperService.checkMappersCompatibility(MapperService.java:385)
	at org.elasticsearch.index.mapper.MapperService.checkMappersCompatibility(MapperService.java:411)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:314)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:272)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:305)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:458)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:762)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

The delete_by_query in the client isn't supported
